### ISSUE TITLE
Oracle Database Connections Failing

### ISSUE THREAD

**Issue by avnsri4986** [Enterprise-connect/ec-springboot-II#1]
Unable to connect to Oracle database. 
Java gives the following error: 
-Could not get JDBC Connection; nested exception is java.sql.SQLException: Listener refused the connection with the following error:
ORA-12520, TNS:listener could not find available handler for requested type of server
The Connection descriptor used by the client was:
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=7990))(LOAD_BALANCE=yes)(FAILOVER=yes)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=pnnpsp04) (FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=1)(DELAY=1))))

where as the EC Windows Library shows the following on console: 
-[EC Server] 2016/12/30 14:12:22 net.TCPConn closed while reading from the resource.
-[EC Server] 2016/12/30 14:12:22 net.TCPConn reached EOF from the io.read.

It's not a database issue since i'm able to connect directly to the database.

**Comment by avnsri4986** [comment]
This issue was fixed with subsequent updates of EC Agent.

**Comment by palokam** [comment]
closing as the issue was fixed
